local M = {}

M.human = {
  { "11", "Aldric", "Elara", "Magnus", "Yara" },
  { "12", "Brennan", "Freya", "Osric", "Thalia" },
  { "13", "Cedric", "Greta", "Piotr", "Vera" },
  { "14", "Drake", "Helena", "Roland", "Wren" },
  { "15", "Edmund", "Isolde", "Silas", "Zara" },
  { "16", "Flynn", "Jasper", "Thea", "Xena" },
  { "21", "Gareth", "Kira", "Ulric", "Ysolde" },
  { "22", "Hugo", "Lyra", "Victor", "Astrid" },
  { "23", "Ivan", "Mira", "Waldemar", "Brunhild" },
  { "24", "Jasper", "Nadia", "Xavier", "Sigrid" },
  { "25", "Kestrel", "Ophelia", "Yorick", "Ingrid" },
  { "26", "Leander", "Petra", "Zephyr", "Katarina" },
  { "31", "Mathis", "Quintus", "Aldric", "Roana" },
  { "32", "Nolan", "Rosalind", "Cedric", "Seren" },
  { "33", "Orion", "Selene", "Drake", "Luna" },
  { "34", "Phineas", "Theron", "Edmund", "Mira" },
  { "35", "Remus", "Ulrika", "Flynn", "Freya" },
  { "36", "Stellan", "Vivian", "Hugo", "Helena" },
  { "41", "Theron", "Wren", "Gareth", "Greta" },
  { "42", "Uriah", "Xanthe", "Ivan", "Isolde" },
  { "43", "Valentin", "Ysolde", "Jasper", "Kira" },
  { "44", "Wolfgang", "Zelda", "Kestrel", "Lyra" },
  { "45", "Xerxes", "Astra", "Leander", "Nadia" },
  { "46", "York", "Briar", "Mathis", "Ophelia" },
  { "51", "Zane", "Clover", "Nolan", "Petra" },
  { "52", "Axel", "Dawn", "Orion", "Quintus" },
  { "53", "Bjorn", "Ember", "Phineas", "Rosalind" },
  { "54", "Colm", "Fern", "Remus", "Selene" },
  { "55", "Dagan", "Glen", "Stellan", "Theron" },
  { "56", "Eamon", "Haven", "Uriah", "Ulrika" },
  { "61", "Finn", "Iris", "Valentin", "Vivian" },
  { "62", "Gunnar", "Juniper", "Wolfgang", "Wren" },
  { "63", "Halvard", "Kestrel", "Xerxes", "Xanthe" },
  { "64", "Ivar", "Lilith", "York", "Ysolde" },
  { "65", "Jarl", "Meadow", "Zane", "Zelda" },
  { "66", "Knut", "Reed", "Axel", "Briar" },
}

M.elf = {
  { "11", "Aelar", "Aerithor" },
  { "12", "Aerendir", "Arilith" },
  { "13", "Aerinwyn", "Arsular" },
  { "14", "Aelric", "Beladria" },
  { "15", "Aranel", "Caelith" },
  { "16", "Baelinor", "Celethor" },
  { "21", "Caelindor", "Elluin" },
  { "22", "Elowen", "Elendrin" },
  { "23", "Elysara", "Firion" },
  { "24", "Galadrel", "Ithelwen" },
  { "25", "Gilraen", "Isolwyn" },
  { "26", "Larethion", "Lunara" },
  { "31", "Lorien", "Lyssara" },
  { "32", "Maerion", "Melariel" },
  { "33", "Mythril", "Nimrodel" },
  { "34", "Orophin", "Raeriel" },
  { "35", "Silvan", "Sylvan" },
  { "36", "Thalion", "Thranduil" },
  { "41", "Vaelindar", "Vaelith" },
  { "42", "Valandil", "Valanthe" },
  { "43", "Vanyra", "Yavanna" },
  { "44", "Aeliana", "Aelinor" },
  { "45", "Arwen", "Celeborn" },
  { "46", "Erestor", "Galadriel" },
  { "51", "Haldir", "Legolas" },
  { "52", "Lindir", "Melian" },
  { "53", "Nimrodel", "Orophin" },
  { "54", "Rumil", "Silvan" },
  { "55", "Tinuviel", "Aelmar" },
  { "56", "Beren", "Celborn" },
  { "61", "Daeron", "Edrahil" },
  { "62", "Egalmoth", "Emeldir" },
  { "63", "Gildor", "Haleth" },
  { "64", "Huor", "Idril" },
  { "65", "Orodreth", "Finduilas" },
  { "66", "Tuor", "Ar-Far" },
}

M.dwarf = {
  { "11", "Thorin", "Dwalin" },
  { "12", "Balin", "Dis" },
  { "13", "Durin", "Disa" },
  { "14", "Nain", "Hildis" },
  { "15", "Moriah", "Thorak" },
  { "16", "Gimor", "Farin" },
  { "21", "Bofur", "Bifur" },
  { "22", "Bombur", "Bombur" },
  { "23", "Gloin", "Glion" },
  { "24", "Oin", "Oina" },
  { "25", "Fili", "Kili" },
  { "26", "Durin", "Mithril" },
  { "31", "Azaghal", "Turgon" },
  { "32", "Gimli", "Glardun" },
  { "33", "Barin", "Dai" },
  { "34", "Dori", "Dorin" },
  { "35", "Nori", "Narin" },
  { "36", "Ori", "Oin" },
  { "41", "Thror", "Thracia" },
  { "42", "Thrain", "Thyra" },
  { "43", "Fror", "Farin" },
  { "44", "Gimilkizdin", "Grorin" },
  { "45", "Kazur", "Kizdin" },
  { "46", "Muzgash", "Nargoth" },
  { "51", "Ralgiol", "Rogvar" },
  { "52", "Rogin", "Rulviel" },
  { "53", "Rumol", "Skaf" },
  { "54", "Traz", "Uzbad" },
  { "55", "Uriz", "Zabaz" },
  { "56", "Durgar", "Grund" },
  { "61", "Kazak", "Thorak" },
  { "62", "Muz", "Durga" },
  { "63", "Skar", "Skaf" },
  { "64", "Urul", "Dag" },
  { "65", "Zogar", "Grimgar" },
  { "66", "Bolg", "Azog" },
}

M.goblin = {
  { "11", "Azug", "Bogmaw" },
  { "12", "Bulgob", "Bumpf" },
  { "13", "Bumnag", "Dudagog" },
  { "14", "Burzob", "Durzol" },
  { "15", "Bumph", "Durgol" },
  { "16", "Dudrurg", "Dogul" },
  { "21", "Frug", "Flim" },
  { "22", "Glugzug", "Grommash" },
  { "23", "Gulfim", "Gobmaw" },
  { "24", "Griznak", "Gunk" },
  { "25", "Grump", "Grime" },
  { "26", "Ichor", "Lumpeye" },
  { "31", "Krab", "Mite" },
  { "32", "Mildew", "Mule" },
  { "33", "Nob", "Pagg" },
  { "34", "Palelegs", "Sicka" },
  { "35", "Scabrot", "Skaggle" },
  { "36", "Skar", "Skar" },
  { "41", "Skrag", "Slugmug" },
  { "42", "Sludger", "Slug" },
  { "43", "Snik", "Snag" },
  { "44", "Smugleg", "Snot" },
  { "45", "Starrog", "Urdus" },
  { "46", "Targ", "Virdok" },
  { "51", "Wartooth", "Skrizzle" },
  { "52", "Zorg", "Torag" },
  { "53", "Gutta", "Kragash" },
  { "54", "Lambug", "Lugnak" },
  { "55", "Morgul", "Naghig" },
  { "56", "Oodagh", "Rundur" },
  { "61", "Thrum", "Baaku" },
  { "62", "Baldrak", "Rulvir" },
  { "63", "Thonna", "Thorgli" },
  { "64", "Morgor", "Grendar" },
  { "65", "Otaan", "Ataan" },
  { "66", "Brogar", "Bashtu" },
}

M.orc = {
  { "11", "Dirdarg", "Lash" },
  { "12", "Delk", "Lurog" },
  { "13", "Murob", "Nargol" },
  { "14", "Pugzag", "Shazgob" },
  { "15", "Smaghed", "Thrashok" },
  { "16", "Xarpug", "Yazgash" },
  { "21", "Zugorim", "Slugga" },
  { "22", "Urgosh", "Bolg" },
  { "23", "Azog", "Gul" },
  { "24", "Bolg", "Gork" },
  { "25", "Gork", "Morgoth" },
  { "26", "Lugdush", "Guritz" },
  { "31", "Shagrat", "Gorbag" },
  { "32", "Mauhur", "Filib" },
  { "33", "Gash", "Kraz" },
  { "34", "Grukk", "Muzgash" },
  { "35", "Borg", "Muz" },
  { "36", "Ugraz", "Zug" },
  { "41", "Muz", "Krul" },
  { "42", "Shag", "Baz" },
  { "43", "Krag", "Grol" },
  { "44", "Grol", "Durzag" },
  { "45", "Snag", "Urg" },
  { "46", "Skar", "Draz" },
  { "51", "Gash", "Mog" },
  { "52", "Kraz", "Thrak" },
  { "53", "Gruk", "Muz" },
  { "54", "Urk", "Gash" },
  { "55", "Mog", "Bolg" },
  { "56", "Draz", "Skul" },
  { "61", "Karg", "Ug" },
  { "62", "Gul", "Mok" },
  { "63", "Rok", "Durg" },
  { "64", "Zug", "Mok" },
  { "65", "Thok", "Gul" },
  { "66", "Azog", "Bolg" },
}

M.halfling = {
  { "11", "Adalgrim", "Aliss" },
  { "12", "Bilbo", "Bella" },
  { "13", "Drogo", "Dora" },
  { "14", "Frodo", "Primula" },
  { "15", "Merimac", "Meriadoc" },
  { "16", "Pippin", "Pearl" },
  { "21", "Samwise", "Rose" },
  { "22", "Merrimac", "Mentha" },
  { "23", "Hamfast", "Hamson" },
  { "24", "Paladin", "Pervinca" },
  { "25", "Faramir", "Diamond" },
  { "26", "Gandalf", "Goldilocks" },
  { "31", "Berilac", "Belba" },
  { "32", "Bingo", "Beryl" },
  { "33", "Bolger", "Camellia" },
  { "34", "Bracegirdle", "Charmain" },
  { "35", "Brambledown", "Daisybelle" },
  { "36", "Brown", "Derrilyn" },
  { "41", "Bundridge", "Elanor" },
  { "42", "Chubb", "Falstuff" },
  { "43", "Cloves", "Gildabrand" },
  { "44", "Digby", "Ginger" },
  { "45", "Folly", "Globul" },
  { "46", "Fox", "Goodbarrel" },
  { "51", "Goodbody", "Hornblower" },
  { "52", "Grace", "Largo" },
  { "53", "Grindley", "Lavender" },
  { "54", "Halfast", "Lily" },
  { "55", "Holdwine", "Marigold" },
  { "56", "Labor", "May" },
  { "61", "Lightfoot", "Melilot" },
  { "62", "Maple", "Molly" },
  { "63", "Overhill", "Peony" },
  { "64", "Proudfoot", "Pimpernel" },
  { "65", "Rug", "Poppy" },
  { "66", "Shortwick", "Rosie" },
}

M.gnome = {
  { "11", "Alston", "Cora" },
  { "12", "Bakister", "Dahlia" },
  { "13", "Belloq", "Elise" },
  { "14", "Beren", "Fiona" },
  { "15", "Caheon", "Galla" },
  { "16", "Chickadee", "Hanna" },
  { "21", "Corg", "Ivy" },
  { "22", "Dallben", "Jasper" },
  { "23", "Elm", "Kylie" },
  { "24", "Erk", "Lila" },
  { "25", "Filio", "Mira" },
  { "26", "Fizban", "Nessa" },
  { "31", "Galain", "Olive" },
  { "32", "Gildas", "Pepper" },
  { "33", "Gnorman", "Rosie" },
  { "34", "Gorob", "Senna" },
  { "35", "Grimsby", "Tansy" },
  { "36", "Han", "Una" },
  { "41", "Hugh", "Verna" },
  { "42", "Ilik", "Wren" },
  { "43", "Kall", "Xena" },
  { "44", "K经验的", "Yara" },
  { "45", "Lilli", "Zoe" },
  { "46", "Lob", "Abelia" },
  { "51", "Milo", "Beryl" },
  { "52", "Myron", "Crystal" },
  { "53", "Nim", "Fern" },
  { "54", "Nodd", "Gemma" },
  { "55", "Orilus", "Honey" },
  { "56", "Osson", "Irene" },
  { "61", "Padraig", "Jade" },
  { "62", "Quar", "Kira" },
  { "63", "Rello", "Luna" },
  { "64", "Rubic", "Misty" },
  { "65", "Sabin", "Nixie" },
  { "66", "Selina", "Opal" },
}

M.troll = {
  { "11", "Rugur", "Ratha" },
  { "12", "Gor", "Morgoth" },
  { "13", "Grukk", "Grash" },
  { "14", "Morg", "Brul" },
  { "15", "Thrak", "Gash" },
  { "16", "Grol", "Muz" },
  { "21", "Korg", "Skar" },
  { "22", "Brul", "Durz" },
  { "23", "Gash", "Mok" },
  { "24", "Skar", "Gul" },
  { "25", "Thrum", "Morg" },
  { "26", "Draz", "Skul" },
  { "31", "Grok", "Krul" },
  { "32", "Mok", "Thrak" },
  { "33", "Durz", "Morg" },
  { "34", "Gul", "Grok" },
  { "35", "Urk", "Skar" },
  { "36", "Zug", "Grol" },
  { "41", "Brog", "Thrum" },
  { "42", "Drog", "Skag" },
  { "43", "Gork", "Mok" },
  { "44", "Krag", "Gul" },
  { "45", "Murk", "Durz" },
  { "46", "Snag", "Urk" },
  { "51", "Zork", "Drog" },
  { "52", "Thok", "Gork" },
  { "53", "Gruk", "Krag" },
  { "54", "Brul", "Murk" },
  { "55", "Skul", "Snag" },
  { "56", "Gul", "Zork" },
  { "61", "Muz", "Thok" },
  { "62", "Gor", "Gruk" },
  { "63", "Korg", "Brul" },
  { "64", "Morg", "Skul" },
  { "65", "Gash", "Gul" },
  { "66", "Bolg", "Azog" },
}

function M.get_name(race)
  race = race or "human"
  local table = M[race] or M.human
  local d66 = require("forge-nvim.dice").d66()
  for _, entry in ipairs(table) do
    if tonumber(entry[1]) == d66 then
      local male = entry[2]
      local female = entry[3] or male
      return math.random() > 0.5 and male or female
    end
  end
  return table[1][2]
end

return M
